### PR TITLE
Merge cortex-m-rt into this repository

### PR DESCRIPTION
**Pull request by adamgreig**
This PR merges the cortex-m-rt repository (with history) into this repo, inside the `cortex-m-rt` folder which is added to the workspace. The main advantage is easier combined testing of cortex-m with cortex-m-rt (including on-hardware tests e.g. #355), and in the future easier changes across the two projects.

The MSRV of cortex-m-rt is bumped 1.39 -> 1.40 to align it with cortex-m itself.

I've updated the CI to run the same tests and checks as before, and updated references to the old URL.

If/after this is merged, I propose adding a note to the old repo's README and then archiving it.

An alternative to this technique would be adding all the files in one new commit (not preserving history), if anyone thinks that would be neater.

NB: This PR also adds an inline to ITM to fix a clippy hard error.

For future reference, the git work was:

```
cd cortex-m-rt
git filter-repo --to-subdirectory-filter cortex-m-rt
cd ../cortex-m
git remote add rt ../cortex-m-rt
git fetch rt
git merge --allow-unrelated-histories rt/master
```

### CODE REVIEW

**Review by thejpster — DISMISSED** [review]

**Review by therealprof — APPROVED** [review]

**Comment by therealprof** [comment]
Let's ship it then?

**Comment by adamgreig** [comment]
sgtm!

bors r=therealprof

**Comment by adamgreig** [comment]
Ugh, why is it failing now but not before... did something change in 1.58 :eyes:

**Comment by adamgreig** [comment]
That should do it :crossed_fingers:

**Comment by thejpster** [comment]
Looks like there's still one red cross?

**Comment by adamgreig** [comment]
Argh, missed that, thanks. Hopefully this fixes it.

**Comment by thejpster** [comment]
Huh. We should probably do daily or weekly builds so we catch this stuff that changes underneath us.

**Comment by adamgreig** [comment]
We do, though currently only for cortex-m: https://github.com/rust-embedded/cortex-m/blob/master/.github/workflows/cron.yml

**Comment by adamgreig** [comment]
OK, green tick!

**Comment by adamgreig** [comment]
I've also added cortex-m-rt's test to the weekly scheduled CI. Hopefully good to merge now.

**Review by thejpster — APPROVED** [review]

**Pull request merged**
