### PR TITLE
Prepare v0.7.4

### PR DESCRIPTION
**Pull request by adamgreig**
I've created a new branch, `v0.7.x`, which is currently at the latest non-breaking commit (so includes #346 #349 #347 #351 #339 #352 #348 #363 #362 #361 but does not include #342), to track the 0.7 series since master now contains breaking changes for v0.8.

This PR (which targets the new branch) cherry-picks #372 #369 #374 and bumps the version to v0.7.4 (and updates CHANGELOG) ready for a new v0.7.4 release. Once complete I'll also backport the changelog entries and bump the version in master to 0.7.4.

I think this is everything that should be in 0.7 -- the only excluded PRs from master are #342 and #367 I believe, and I don't think we have any open PRs targeting 0.7 either.

Any other thoughts on items for inclusion in 0.7.4 (or other changelog entries I missed)?

### CODE REVIEW

**Comment by TDHolmes** [comment]
LGTM, but wanted to ask, the bin files are much smaller now. Did we notice that back when the inline asm changes were originally updated? I see you said:
> With this change the disassembly output is identical to what we have now (phew).

so are the file size changes all just like debug info?

**Comment by adamgreig** [comment]
Good spot, that is kind of alarming. I'll check.

**Comment by adamgreig** [comment]
I think this is mostly a quirk of GitHub's UI - the percentage in red is the new size relative to the old size, not the size of the delta, so `-1.73 KB (89%)` means the new 14kB file is 1.73kB smaller than the old 16kB file, but we haven't lost 89% of the contents. Checking the archive files manually the difference does seem to be mostly in some tweaked debug info and various other apparently minor changes due to the new LLVM version. Overall doesn't look like a problem.

**Review by thejpster — APPROVED** [review]
LGTM

**Comment by adamgreig** [comment]
OK, let's get this out there.

bors r=thejpster

**Pull request merged**
