### PR TITLE
 Fix __delay asm function for the thumbv6m-none-eabi target 

### PR DESCRIPTION
**Pull request by Disasm**
Before:
```
00000000 <__delay>:
   0:	46c0      	nop			; (mov r8, r8)
   2:	3801      	subs	r0, #1
   4:	d1fe      	bne.n	0 <__delay>
			4: R_ARM_THM_JUMP8	__delay
   6:	4770      	bx	lr
```

After:
```
00000000 <__delay>:
   0:	46c0      	nop			; (mov r8, r8)
   2:	3801      	subs	r0, #1
   4:	d1fc      	bne.n	0 <__delay>
   6:	4770      	bx	lr
```

Closes https://github.com/rust-embedded/cortex-m/issues/125

### CODE REVIEW

**Comment by therealprof** [comment]
@Disasm The file sizes of the binaries are weird. Can you show a before/after objdump of thumbv7m and thumbv8m.main?

**Comment by Disasm** [comment]
`diff -c thumbv7m-none-eabi.before thumbv7m-none-eabi.after`:
```diff
*** thumbv7m-none-eabi.before	2019-07-05 00:53:44.912959913 +0300
--- thumbv7m-none-eabi.after	2019-07-05 00:54:32.731009376 +0300
***************
*** 32,39 ****
  00000000 <__delay>:
     0:	bf00      	nop
     2:	3801      	subs	r0, #1
!    4:	f47f affe 	bne.w	0 <__delay>
!    8:	4770      	bx	lr
  
  Disassembly of section .text.__dmb:
  
--- 32,39 ----
  00000000 <__delay>:
     0:	bf00      	nop
     2:	3801      	subs	r0, #1
!    4:	d1fc      	bne.n	0 <__delay>
!    6:	4770      	bx	lr
  
  Disassembly of section .text.__dmb:

```

`diff -c thumbv8m.main-none-eabi.before thumbv8m.main-none-eabi.after`:
```diff
*** thumbv8m.main-none-eabi.before	2019-07-05 00:53:44.919626307 +0300
--- thumbv8m.main-none-eabi.after	2019-07-05 00:54:32.737675770 +0300
***************
*** 32,39 ****
  00000000 <__delay>:
     0:	bf00      	nop
     2:	3801      	subs	r0, #1
!    4:	f47f affe 	bne.w	0 <__delay>
!    8:	4770      	bx	lr
  
  Disassembly of section .text.__dmb:
  
--- 32,39 ----
  00000000 <__delay>:
     0:	bf00      	nop
     2:	3801      	subs	r0, #1
!    4:	d1fc      	bne.n	0 <__delay>
!    6:	4770      	bx	lr
  
  Disassembly of section .text.__dmb:

```

".before" files were created on the `master` branch and ".after" - on this PR branch.

**Comment by Disasm** [comment]
Also just regenerating the binaries on master increases `thumbv8m.main-none-eabi.a` archive size by 150 bytes.

**Comment by therealprof** [comment]
Okay then.

**Pull request merged**
