### PR TITLE
scb: add static version of system_reset as sys_reset

### PR DESCRIPTION
**Pull request by hdhoang**
As suggested in https://github.com/ah-/anne-key/pull/94. I branched this off v0.5.8 to verify the function in that PR, and against rtfm v0.3 in https://github.com/hdhoang/anne-key/commit/d6fb831cbbb46bc10a6184b78bf13e00245234d6

I have cloned the body of `system_reset`, do you think we should call one from the other (e.g. ignoring `self` in `system_reset`, or stealing `Peripherals` in `system_reset2`)?

### CODE REVIEW

**Comment by hdhoang** [comment]
hi team! could someone take a look?

**Comment by korken89** [comment]
Hi, overall I think this looks good, however I'm not 100% sure of the name.
But I have no strong opinion there, the documentation says that it is a static version.

Any comments against @rust-embedded/cortex-m ? Else I will approve and merge this today.

**Comment by adamgreig** [comment]
Much as I hate to suggest a new breaking change so soon after 0.6, I wonder if `system_reset` would be better as a single static function, so remove self from the current `system_reset` and don't have `system_reset2`. Perhaps we could do that in 0.7, mark `system_reset` as deprecated, and maybe call the new static function `sys_reset` rather than `system_reset2`?

**Comment by azasypkin** [comment]
> Perhaps we could do that in 0.7, mark system_reset as deprecated, and maybe call the new static function sys_reset rather than system_reset2?

Sorry for hijacking, but if we go this route, it'd probably make sense to do the same for `set_deepsleep/clear_deepsleep` as briefly discussed in https://github.com/japaric/cortex-m-rtfm/issues/165. It will be a bit more difficult to come up with new names in this case though.

**Comment by korken89** [comment]
I agree on only having a static version as it makes sense.
But it does not hurt to have both and backwards compatibility, so I have no strong opinion on deprecating the existing API.

What does @therealprof or @japaric think?

**Comment by japaric** [comment]
IMO, it makes sense to add this static method and deprecate the old `system_reset` method using the `#[deprecated]` attribute in a new patch version (i.e. v0.6.1). (Deprecating things does not warrant a semver bump -- yes, deprecating things will trigger `deny(warning)` errors but only of things you have the source code at hand; crates that come from crates.io will not error (module compiler bugs))

**Comment by hdhoang** [comment]
I could add the deprecation warning and a TODO to rename the `system_reset2` as well. The same method would also apply cleanly to static deepsleep functions.

**Comment by adamgreig** [comment]
Are you suggesting we call the new static function `system_reset2` for now, then once we've removed `system_reset` and replaced it with the new static function, we leave a proxy `system_reset2` in but deprecated and remove it in another release?

It's sort of nice in that we end up with just `system_reset` as a static function but it does mean two deprecated items/breaking changes. It would also help avoid needing to find new names for the deepsleep functions.

**Comment by therealprof** [comment]
I'm not too attached to `system_reset` so adding `sys_reset` and deprecating the former is okay for me.

**Comment by hdhoang** [comment]
I have incorporated your feedbacks, thanks!

**Comment by korken89** [comment]
I'm also quite ok with what @therealprof said

**Comment by korken89** [comment]
I think this is close enough for naming, we can bike-shed this forever :)

**Pull request merged**
