### PR TITLE
Prevent underflow when calling delay(n) with n<2

### PR DESCRIPTION
**Pull request by ovidiusabou**
Calling delay(1) causes a very long wait (freeze) otherwise.
86cd463788b97ca3894936101c6cf4f3512f0fbc introduced this behaviour by
changing the cycle count from n / 4 + 1 to n / 2 which forces an
underflow when n<2.

### CODE REVIEW

**Review by jonas-schievink — DISMISSED** [review]
Change looks good to me, thanks! Can you add a short comment explaining why we add 1?

**Comment by jonas-schievink** [comment]
Also, run `cargo xtask assemble` to update the blobs, then CI should pass

**Comment by ovidiusabou** [comment]
I ran `cargo xtask assemble` but CI still doesn't pass.

**Comment by jonas-schievink** [comment]
If I run it locally it still changes the archives. What OS are you on?

**Comment by ovidiusabou** [comment]
Mac OS

**Comment by ovidiusabou** [comment]
```
~/Projects/cortex-m fix-delay-underflow ❯ git status
On branch fix-delay-underflow
Your branch is up to date with 'origin/fix-delay-underflow'.

nothing to commit, working tree clean
~/Projects/cortex-m fix-delay-underflow ❯ cargo xtask assemble
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/xtask assemble`
info: component 'rust-std' for target 'thumbv6m-none-eabi' is up to date
info: component 'rust-std' for target 'thumbv7m-none-eabi' is up to date
info: component 'rust-std' for target 'thumbv7em-none-eabi' is up to date
info: component 'rust-std' for target 'thumbv7em-none-eabihf' is up to date
info: component 'rust-std' for target 'thumbv8m.base-none-eabi' is up to date
info: component 'rust-std' for target 'thumbv8m.main-none-eabi' is up to date
info: component 'rust-std' for target 'thumbv8m.main-none-eabihf' is up to date
building artifacts for thumbv6m-none-eabi
"rustc" "+nightly-2020-08-26" "--target" "thumbv6m-none-eabi" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-o" "bin/thumbv6m-none-eabi.o" "asm/lib.rs"
"rustc" "+nightly-2020-08-26" "--target" "thumbv6m-none-eabi" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-Clinker-plugin-lto" "-o" "bin/thumbv6m-none-eabi-lto.o" "asm/lib.rs"
building artifacts for thumbv7m-none-eabi
"rustc" "+nightly-2020-08-26" "--target" "thumbv7m-none-eabi" "--cfg=armv7m" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-o" "bin/thumbv7m-none-eabi.o" "asm/lib.rs"
"rustc" "+nightly-2020-08-26" "--target" "thumbv7m-none-eabi" "--cfg=armv7m" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-Clinker-plugin-lto" "-o" "bin/thumbv7m-none-eabi-lto.o" "asm/lib.rs"
building artifacts for thumbv7em-none-eabi
"rustc" "+nightly-2020-08-26" "--target" "thumbv7em-none-eabi" "--cfg=armv7m" "--cfg=armv7em" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-o" "bin/thumbv7em-none-eabi.o" "asm/lib.rs"
"rustc" "+nightly-2020-08-26" "--target" "thumbv7em-none-eabi" "--cfg=armv7m" "--cfg=armv7em" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-Clinker-plugin-lto" "-o" "bin/thumbv7em-none-eabi-lto.o" "asm/lib.rs"
building artifacts for thumbv7em-none-eabihf
"rustc" "+nightly-2020-08-26" "--target" "thumbv7em-none-eabihf" "--cfg=armv7m" "--cfg=armv7em" "--cfg=has_fpu" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-o" "bin/thumbv7em-none-eabihf.o" "asm/lib.rs"
"rustc" "+nightly-2020-08-26" "--target" "thumbv7em-none-eabihf" "--cfg=armv7m" "--cfg=armv7em" "--cfg=has_fpu" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-Clinker-plugin-lto" "-o" "bin/thumbv7em-none-eabihf-lto.o" "asm/lib.rs"
building artifacts for thumbv8m.base-none-eabi
"rustc" "+nightly-2020-08-26" "--target" "thumbv8m.base-none-eabi" "--cfg=armv8m" "--cfg=armv8m_base" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-o" "bin/thumbv8m.base-none-eabi.o" "asm/lib.rs"
"rustc" "+nightly-2020-08-26" "--target" "thumbv8m.base-none-eabi" "--cfg=armv8m" "--cfg=armv8m_base" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-Clinker-plugin-lto" "-o" "bin/thumbv8m.base-none-eabi-lto.o" "asm/lib.rs"
building artifacts for thumbv8m.main-none-eabi
"rustc" "+nightly-2020-08-26" "--target" "thumbv8m.main-none-eabi" "--cfg=armv7m" "--cfg=armv8m" "--cfg=armv8m_main" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-o" "bin/thumbv8m.main-none-eabi.o" "asm/lib.rs"
"rustc" "+nightly-2020-08-26" "--target" "thumbv8m.main-none-eabi" "--cfg=armv7m" "--cfg=armv8m" "--cfg=armv8m_main" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-Clinker-plugin-lto" "-o" "bin/thumbv8m.main-none-eabi-lto.o" "asm/lib.rs"
building artifacts for thumbv8m.main-none-eabihf
"rustc" "+nightly-2020-08-26" "--target" "thumbv8m.main-none-eabihf" "--cfg=armv7m" "--cfg=armv8m" "--cfg=armv8m_main" "--cfg=has_fpu" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-o" "bin/thumbv8m.main-none-eabihf.o" "asm/lib.rs"
"rustc" "+nightly-2020-08-26" "--target" "thumbv8m.main-none-eabihf" "--cfg=armv7m" "--cfg=armv8m" "--cfg=armv8m_main" "--cfg=has_fpu" "-g" "-O" "-Clto=yes" "-Cforce-frame-pointers=no" "--remap-path-prefix" "/Users/ovidiu/Projects/cortex-m=." "--emit=obj" "-Clinker-plugin-lto" "-o" "bin/thumbv8m.main-none-eabihf-lto.o" "asm/lib.rs"
~/Projects/cortex-m fix-delay-underflow ❯ git status
On branch fix-delay-underflow
Your branch is up to date with 'origin/fix-delay-underflow'.

nothing to commit, working tree clean
~/Projects/cortex-m fix-delay-underflow ❯ git push
Everything up-to-date
~/Projects/cortex-m fix-delay-underflow ❯
```

**Review by jonas-schievink — APPROVED** [review]
bors r+

**Comment by David-OConnor** [comment]
I can confirm this. Just started getting it on the f3 hal's `adc` setup; not sure why it just started.

**Comment by adamgreig** [comment]
> I can confirm this. Just started getting it on the f3 hal's `adc` setup.

This should have been fixed in cortex-m 0.7.1 which was released a while back, what version of cortex-m are you using?

**Comment by David-OConnor** [comment]
I tried versions 0.6.5, 0.7.0, and 0.7.1. The most recent version I had been using where it worked was 0.6.4.

This function in `adc.rs` was crashing it:
```rust
fn wait_advregen_startup(&self) {
    asm::delay(MAX_ADVREGEN_STARTUP_US * 1_000_000) / self.clocks.sysclk().0);
}
```

I patched it to be, which fixed it:
```rust
fn wait_advregen_startup(&self) {
    let mut delay = (MAX_ADVREGEN_STARTUP_US * 1_000_000) / self.clocks.sysclk().0;
    if delay < 2 {
        delay = 2;
    }
    asm::delay(delay);
}
```

**Comment by ovidiusabou** [comment]
0.7.1 doesn't include the fix from this PR from what I can see.

**Comment by adamgreig** [comment]
Oops, you're quite right, I was thinking of https://github.com/rust-embedded/cortex-m/pull/317 instead. Are you able to test with cortex-m master from this repository?

**Pull request merged**
