### PR TITLE
Prepare for cortex-m-rt 0.7.5

### LINKED ISSUE #532: HardFault handler is completely broken in c-m-rt 0.7.4
cortex-m-rt 0.7.4 changes the exception macro so that hardfaults now have an *optional* trampoline argument. If the argument isn't given, the exception frame reference isn't passed.

Unfortunately the macro crate wasn't published, and cortex-m-rt has a tight pin on the old version: 0.7.0

This means if you use the exception frame argument, the reference will get a garbage value. This causes a failure *inside the hard fault handler*, putting the CPU into a lock-up state.

We need to publish the cortex-m-rt-macros crate, yank cortex-m-rt 0.7.4, and publish 0.7.5 with a pin on the new macro crate. And then somehow update the docs / write some tests so that in future it's much more difficult to release cortex-m-rt with the wrong version of the macro crate.

### PR DESCRIPTION
**Pull request by adamgreig**
Fixes #532.

### CODE REVIEW

**Review by thejpster — APPROVED** [review]

**Comment by thejpster** [comment]
Before we do the releases, have we checked that the new macro works as expected and rejects mismatched hard fault signatures?

**Comment by diondokter** [comment]
> Before we do the releases, have we checked that the new macro works as expected and rejects mismatched hard fault signatures?

Tests were added: https://github.com/rust-embedded/cortex-m/blob/master/cortex-m-rt/tests/compile-fail/hard-fault-bad-signature-3.rs
There are more too.

It doesn't pick up on unreleased macro crate releases because it defines the dependency with a path:
https://github.com/rust-embedded/cortex-m/blob/4395baee03d57a4e1763c427073da5f33ec3b17e/cortex-m-rt/Cargo.toml#L21-L22
This is probably the correct way in this crate, but yeah it does make it easy to forget to release any new version of it.

**Comment by jonathanpallant** [comment]
I think one solution for this is for the main branch to be changed to have the version number `N + 1` right after version `N` is released, and for any dependencies within the same repo to also use `N + 1` as a version number.

**Comment by jamesmunns** [comment]
Also noting that @newAM successfully yanked v0.7.4 - we should probably note this in the release docs that we are fixing those regression(s).

**Comment by newAM** [comment]
I rebased this branch to fix CI and resolve conflicts.

**Review by newAM — APPROVED** [review]
I missed that this PR got blocked await a review after thejpster left as a member.  I'm not sure how to evaluate the risk of #535, will wait for other cortex-m members to help evaluate that.

**Comment by adamgreig** [comment]
I've rebased and updated the changelog with the various changes. Should be ready to go now.

**Review by newAM — APPROVED** [review]

**Pull request merged**
