### PR TITLE
Add MSRV note to README

### PR DESCRIPTION
**Pull request by adamgreig**
Ref. https://github.com/rust-embedded/wg/issues/445

### CODE REVIEW

**Comment by adamgreig** [comment]
We've hit #204  and all nightly builds are now failing due to `llvm_asm!`. We should mark nightly builds as allowed to fail.

**Comment by adamgreig** [comment]
I've updated the PR to also allow failures on nightly builds.

**Comment by adamgreig** [comment]
bors retry

**Comment by adamgreig** [comment]
@korken89 I've rebased the PR, could you re-review please?

**Comment by therealprof** [comment]
bors retry

**Comment by therealprof** [comment]
bors retry

**Comment by adamgreig** [comment]
bors retry

**Pull request merged**
