### PR TITLE
Generate debug information for assembly functions

### PR DESCRIPTION
**Pull request by Tiwalun**
This helps with debugging, but makes the binaries a bit larger.

### CODE REVIEW

**Comment by adamgreig** [comment]
To be clear: this makes our object files larger, but shouldn't have any impact on application code size, right?

**Comment by Tiwalun** [comment]
It makes the final ELF files bigger, the debug information for the assembly function will always be there, regardless of the rustc settings.

The actual code size without debug information is unchanged. For an embedded context, this is probably more relevant.

**Comment by adamgreig** [comment]
Sorry, yes, I mean "the final occupied space in the target flash" is unchanged, whereas we don't really care if the elfs are a few bytes larger.

**Comment by adamgreig** [comment]
We'll have to wait for #214 which I thought would merge before this.

**Comment by adamgreig** [comment]
bors retry

**Comment by adamgreig** [comment]
bors retry

**Pull request merged**
