### PR TITLE
Prepare 0.6.4

### PR DESCRIPTION
**Pull request by adamgreig**
Includes #274 to fix recent issues with inline-asm on nightly.

### CODE REVIEW

**Review by jonas-schievink — APPROVED** [review]
bors r+

**Comment by adamgreig** [comment]
bors retry

**Comment by adamgreig** [comment]
Looks like Travis is just being slow triggering some builds. If this one doesn't take I'll try again tonight or something.

bors retry

**Comment by adamgreig** [comment]
bors retry

**Comment by adamgreig** [comment]
Released!

**Pull request merged**
